name: Update

on:
  schedule:
    - cron: "0 6 * * 6" # every saturday at 6am
  workflow_dispatch:
    inputs: 
      - ignore_update_check: 
        description: "Ignore update check?"
        required: true
        default: true
        type: boolean
      - override_version: 
        description: "Override version to check"
        required: false
        default: ""
        type: string

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    outputs:
      id: ${{steps.check.outputs.id}}
    steps:
      - id: check
        name: Check for Minecraft Updates
        uses: ByMartrixX/minecraft-update-check-action@v0
        with:
          version-manifest-url: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
          cache-base-key: 'mc-manifest-'
  
  update:
    runs-on: ubuntu-latest
    needs: check_for_updates
    if: ${{needs.check_for_updates.outputs.id != '' || github.event.inputs.ignore_update_check}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Git
        uses: fregante/setup-git-user@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: "npm"

      - name: Run Generator
        run: |
          node generator/generator.js ${{github.events.inputs.override_version ? github.events.inputs.override_version : needs.check_for_updates.outputs.id}}

      - name: Push Tag
        run: |
          version=${{github.events.inputs.override_version ? github.events.inputs.override_version : needs.check_for_updates.outputs.id}}
          git add .
          git commit -m $version
          git tag -a $version -m $version
          git push --follow-tags